# Full stack docker compose
# Remove web/firebase components for prod

version: '3'
services:
  sandbox1:
    image: nutc-exchange
    build:
      context: ../..
      dockerfile: exchange/docker/sandbox/Dockerfile
    restart: unless-stopped
    environment:
      - NUTC_EXPOSE_METRICS=1
      - NUTC_ALGO_ENDPOINT=http://webserver:16124/algorithms/HFT
      - NUTC_ID=0
    depends_on:
      - webserver
  # sandbox2:
  #   image: nutc-exchange
  #   build:
  #     context: ../..
  #     dockerfile: exchange/docker/sandbox/Dockerfile
  #   restart: unless-stopped
  #   environment:
  #     - NUTC_EXPOSE_METRICS=1
  #     - NUTC_ALGO_ENDPOINT=http://webserver:16124/algorithms/HFT
  #     - NUTC_ID=1
  #   depends_on:
  #     - webserver
  # sandbox3:
  #   image: nutc-exchange
  #   build:
  #     context: ../..
  #     dockerfile: exchange/docker/sandbox/Dockerfile
  #   restart: unless-stopped
  #   environment:
  #     - NUTC_EXPOSE_METRICS=1
  #     - NUTC_ALGO_ENDPOINT=http://webserver:16124/algorithms/HFT
  #     - NUTC_ID=2
  #   depends_on:
  #     - webserver
  sandbox4:
    image: nutc-exchange
    build:
      context: ../..
      dockerfile: exchange/docker/sandbox/Dockerfile
    restart: unless-stopped
    environment:
      - NUTC_EXPOSE_METRICS=1
      - NUTC_ALGO_ENDPOINT=http://webserver:16124/algorithms/HFT
      - NUTC_ID=3
    depends_on:
      - webserver
    # command: ["--sandbox"]

    #port: 16124
  webserver:
    image: nutc-webserver
    build:
      context: ../..
      dockerfile: webserver/Dockerfile
    restart: unless-stopped

  # Exposed on port 9000
  prometheus:
    image: prom/prometheus
    volumes:
      - ../../exchange/docker/sandbox/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=12h'
    restart: unless-stopped


  grafana:
    image: grafana/grafana
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - "3000:3000"
    environment:
    - GF_SECURITY_ALLOW_EMBEDDING=true
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_NAME=MAIN
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ../../exchange/docker/dev/grafana_data:/var/lib/grafana
      # - /var/lib/grafana/grafana.db
      # - /var/lib/grafana/alerting
