version: '3.8'

services:
  web:
    image: node:latest
    working_dir: /app
    volumes:
      - ..:/app
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/var/lib/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_FORCE_PATH_STYLE=true
    volumes:
     - localstack:/var/lib/localstack

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nutc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma-studio:
    image: node:latest
    working_dir: /app
    volumes:
      - ..:/app
    command: ["npx", "prisma", "studio"]
    ports:
      - "5555:5555"  # You can customize this port if needed
    depends_on:
      - postgres

volumes:
  postgres_data:
  localstack:
