global:
    starting_capital: 100000
    # How long to wait after exchange-wrapper handshake before wrappers can place orders
    wait_secs: 3

    order_fee: .0000
    sandbox_trial_seconds: 300
    max_cumulative_order_volume: 5000

tickers:
  - ticker: "ETH"
    start_price: 100
    bots:
      - type: "market_maker"
        number_of_bots: 50
        average_capital: 200000
        std_dev_capital: 50000
      - type: "retail"
        number_of_bots: 250
        average_capital: 5000
        std_dev_capital: 2000

        # perfect: 5/250000/5000, 25/1000/200
  - ticker: "LTC"
    start_price: 50
    bots:
      - type: "market_maker"
        number_of_bots: 5
        average_capital: 200000
        std_dev_capital: 50000
      - type: "retail"
        number_of_bots: 25
        average_capital: 5000
        std_dev_capital: 2000

  - ticker: "BTC"
    start_price: 200
    bots:
      - type: "market_maker"
        number_of_bots: 25
        average_capital: 200000
        std_dev_capital: 50000
      - type: "retail"
        number_of_bots: 125
        average_capital: 5000
        std_dev_capital: 2000
