services:
  # Exposed on port 9000
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"

    # allow prometheus to access exchange on the host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=12h'
    restart: unless-stopped
    networks:
      - net

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    user: "472:472"
    ports:
      - "3000:3000"
    environment:
    - GF_SECURITY_ALLOW_EMBEDDING=true
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_NAME=MAIN
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./docker/grafana_data:/var/lib/grafana
    networks:
      - net

networks:
  net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
