version: '3'

env:
  NAME: NUTC-linter

tasks:
  deps:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - conan install . -s build_type=Debug -b missing -pr cpp20 -pr:b cpp20

  format:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmake -D FIX=YES -P cmake/lint.cmake
    
  init:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f CMakeUserPresets.json
    cmds:
      - cmake --preset=dev

  build:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f CMakeUserPresets.json
    cmds:
      - cmake --build --preset=dev -j

  build-local-dev:
    preconditions:
      - test -f CMakeUserPresets.json
    cmds:
      - cmake --preset=dev -DNUTC_LINTER_LOCAL_DEV_MODE=ON
      - cmake --build --preset=dev -j

  run-dev:
    cmds:
      - task: build-local-dev
      - sudo mv ./build/dev/{{.NAME}}-spawner /usr/local/bin/{{.NAME}}-spawner
      - ./build/dev/{{.NAME}} 
  run-v:
    env:
      SPDLOG_LEVEL: trace
    cmds:
      - task: run

  test:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: build
      - ctest --preset=dev

  docs:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmake --build --preset=dev -t docs
      - cmake --build --preset=dev -t docs-serve

  clean:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmake --build --preset=dev -t clean

  format:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmake -D FIX=YES -P cmake/lint.cmake

  default:
    cmds:
      - task: run
