# Full stack docker compose
# Remove web/firebase components for prod

version: '3'
services:
  sandbox:
    image: nutc-exchange
    build:
      context: ../..
      dockerfile: exchange/docker/sandbox/Dockerfile
      args:
        firebase_emulator: "false"
    restart: unless-stopped
    environment:
      - NUTC_EXPOSE_METRICS=1
    command: ["--sandbox"]

    #port: 16124
  webserver:
    image: nutc-webserver
    build:
      context: ../..
      dockerfile: webserver/Dockerfile
    restart: unless-stopped

  linter:
    image: nutc-linter
    restart: unless-stopped
    build:
      context: ../..
      dockerfile: exchange/docker/linter/Dockerfile
      args:
        firebase_emulator: "false"

  # Exposed on port 9000
  prometheus:
    image: prom/prometheus
    volumes:
      - ../../exchange/docker/sandbox/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=12h'
    restart: unless-stopped

  reverse-proxy:
    image: nginx:latest
    ports:
      - "26389:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    depends_on:
      - webserver
      - grafana

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - "3000:3000"
    environment:
    - GF_SECURITY_ALLOW_EMBEDDING=true
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_NAME=MAIN
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ../../exchange/docker/dev/grafana_data:/var/lib/grafana
      # - /var/lib/grafana/grafana.db
      # - /var/lib/grafana/alerting
