version: '3'

env:
  NAME: NUTC-client

tasks:
  deps:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - conan install . -s build_type=Debug -b missing -pr cpp20 -pr:b cpp20
    
  init:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f CMakeUserPresets.json
    cmds:
      - cmake --preset=dev

  move-to-bin:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: build
      - sudo cp ./build/dev/{{.NAME}} /usr/local/bin/

  build:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f CMakeUserPresets.json
    cmds:
      - cmake --build --preset=dev -j

  run:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: build
      - ./build/dev/{{.NAME}} --uid "nsogzsFY6LVgnvC615TrbJ2XjXR2"

  run-v:
    env:
      SPDLOG_LEVEL: trace
    cmds:
      - task: run

  test:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: build
      - ctest --preset=dev

  docs:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmake --build --preset=dev -t docs
      - cmake --build --preset=dev -t docs-serve

  clean:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmake --build --preset=dev -t clean

  default:
    cmds:
      - task: run
