version: '3.8'

services:
  web:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nutc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
